-- TW 지역 시즌별 데이터 확인
-- 2026-02-11 기준으로 YoY 계산 시 사용되는 데이터 검증

-- 1. TW 매장 목록
SELECT DISTINCT LOCAL_SHOP_CD, BRD_CD
FROM SAP_FNF.DW_HMD_SALE_D
WHERE LOCAL_SHOP_CD LIKE 'T%' OR LOCAL_SHOP_CD LIKE 'D%'
ORDER BY LOCAL_SHOP_CD;

-- 2. TW 시즌별 매출 데이터 확인 (M 브랜드)
SELECT 
  SESN,
  COUNT(DISTINCT PRDT_CD) AS product_count,
  COUNT(DISTINCT LOCAL_SHOP_CD) AS store_count,
  SUM(TAG_SALE_AMT) AS total_sales,
  MIN(SALE_DT) AS first_date,
  MAX(SALE_DT) AS last_date
FROM SAP_FNF.DW_HMD_SALE_D
WHERE (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND (LOCAL_SHOP_CD LIKE 'T%' OR LOCAL_SHOP_CD LIKE 'TE%')
  AND SESN IN ('24F', '25F')
GROUP BY SESN
ORDER BY SESN;

-- 3. TW 카테고리별 매출 (의류만, 25F vs 24F)
-- 의류 카테고리: 소분류 2자리가 특정 코드 (예: 10, 11, 12 등)
SELECT 
  SESN,
  SUBSTR(PART_CD, 3, 2) AS category_code,
  COUNT(DISTINCT PRDT_CD) AS product_count,
  SUM(TAG_SALE_AMT) AS total_sales
FROM SAP_FNF.DW_HMD_SALE_D
WHERE (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND (LOCAL_SHOP_CD LIKE 'T%' OR LOCAL_SHOP_CD LIKE 'TE%')
  AND SESN IN ('24F', '25F')
  AND SALE_DT BETWEEN '2024-09-01' AND '2026-02-11'
GROUP BY SESN, SUBSTR(PART_CD, 3, 2)
ORDER BY SESN, category_code;

-- 4. 특정 카테고리의 YoY 비교 (예: 의류 카테고리 10)
SELECT 
  SESN,
  SUBSTR(PART_CD, 3, 2) AS category,
  SUM(TAG_SALE_AMT) AS sales,
  COUNT(DISTINCT PRDT_CD) AS products
FROM SAP_FNF.DW_HMD_SALE_D
WHERE (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND (LOCAL_SHOP_CD LIKE 'T%' OR LOCAL_SHOP_CD LIKE 'TE%')
  AND SESN IN ('24F', '25F')
  AND SUBSTR(PART_CD, 3, 2) IN ('10', '11') -- 의류 카테고리 예시
  AND SALE_DT <= '2026-02-11'
GROUP BY SESN, SUBSTR(PART_CD, 3, 2)
ORDER BY SESN, category;

-- 5. 재고 데이터 확인
SELECT 
  SESN,
  SUBSTR(PART_CD, 3, 2) AS category,
  MAX(STOCK_DT) AS latest_stock_dt,
  SUM(TAG_STOCK_AMT) AS total_stock,
  COUNT(DISTINCT PRDT_CD) AS products
FROM SAP_FNF.DW_HMD_STOCK_SNAP_D
WHERE (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND (LOCAL_SHOP_CD LIKE 'T%' OR LOCAL_SHOP_CD LIKE 'D%')
  AND SESN IN ('24F', '25F')
  AND STOCK_DT <= DATEADD(DAY, 1, '2026-02-11')
  AND SUBSTR(PART_CD, 3, 2) IN ('10', '11')
GROUP BY SESN, SUBSTR(PART_CD, 3, 2)
ORDER BY SESN, category;
