-- TW 1월 25F 의류 - 다양한 판매액 컬럼 비교

WITH apparel_categories AS (
  SELECT 'DP' AS cat UNION ALL SELECT 'LG' UNION ALL SELECT 'PT' UNION ALL SELECT 'SK' 
  UNION ALL SELECT 'SM' UNION ALL SELECT 'SP' UNION ALL SELECT 'TP' UNION ALL SELECT 'WP'
  UNION ALL SELECT 'BS' UNION ALL SELECT 'HD' UNION ALL SELECT 'KP' UNION ALL SELECT 'MT' 
  UNION ALL SELECT 'OP' UNION ALL SELECT 'PQ' UNION ALL SELECT 'TK' UNION ALL SELECT 'TR' 
  UNION ALL SELECT 'TS' UNION ALL SELECT 'WS'
  UNION ALL SELECT 'DJ' UNION ALL SELECT 'DK' UNION ALL SELECT 'FD' UNION ALL SELECT 'JP' 
  UNION ALL SELECT 'KC' UNION ALL SELECT 'WJ' UNION ALL SELECT 'S6'
  UNION ALL SELECT 'DS' UNION ALL SELECT 'DD' UNION ALL SELECT 'DR' UNION ALL SELECT 'RS' 
  UNION ALL SELECT 'SW' UNION ALL SELECT 'TO' UNION ALL SELECT 'DV' UNION ALL SELECT 'JK' 
  UNION ALL SELECT 'KT' UNION ALL SELECT 'PD' UNION ALL SELECT 'VT'
  UNION ALL SELECT 'DT' UNION ALL SELECT 'S2' UNION ALL SELECT 'S1' UNION ALL SELECT 'BV' 
  UNION ALL SELECT 'ZT' UNION ALL SELECT 'CT' UNION ALL SELECT 'LE' UNION ALL SELECT 'S5' 
  UNION ALL SELECT 'RL' UNION ALL SELECT 'SS' UNION ALL SELECT 'TL' UNION ALL SELECT 'BR'
)

SELECT 
  'TAG_SALE_AMT (택가매출)' AS column_name,
  SUM(TAG_SALE_AMT) AS total_twd,
  SUM(TAG_SALE_AMT) * 0.2475 AS total_hkd
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3','TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories)

UNION ALL

SELECT 
  'VAT_EXC_ACT_SALE_AMT (부가세제외실판매)',
  SUM(VAT_EXC_ACT_SALE_AMT),
  SUM(VAT_EXC_ACT_SALE_AMT) * 0.2475
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3','TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories)

UNION ALL

SELECT 
  'ACT_SALE_AMT (실판매)',
  SUM(ACT_SALE_AMT),
  SUM(ACT_SALE_AMT) * 0.2475
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3','TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories)

UNION ALL

SELECT 
  'SALE_AMT (매출)',
  SUM(SALE_AMT),
  SUM(SALE_AMT) * 0.2475
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3','TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories);
