-- TW 리전 2026년 1월 (25F 의류만) 택가매출 vs 실판매출 확인
-- 트리맵 API가 사용하는 것과 동일한 로직

WITH apparel_categories AS (
  SELECT 'DP' AS cat UNION ALL SELECT 'LG' UNION ALL SELECT 'PT' UNION ALL SELECT 'SK' 
  UNION ALL SELECT 'SM' UNION ALL SELECT 'SP' UNION ALL SELECT 'TP' UNION ALL SELECT 'WP'
  UNION ALL SELECT 'BS' UNION ALL SELECT 'HD' UNION ALL SELECT 'KP' UNION ALL SELECT 'MT' 
  UNION ALL SELECT 'OP' UNION ALL SELECT 'PQ' UNION ALL SELECT 'TK' UNION ALL SELECT 'TR' 
  UNION ALL SELECT 'TS' UNION ALL SELECT 'WS'
  UNION ALL SELECT 'DJ' UNION ALL SELECT 'DK' UNION ALL SELECT 'FD' UNION ALL SELECT 'JP' 
  UNION ALL SELECT 'KC' UNION ALL SELECT 'WJ' UNION ALL SELECT 'S6'
  UNION ALL SELECT 'DS' UNION ALL SELECT 'DD' UNION ALL SELECT 'DR' UNION ALL SELECT 'RS' 
  UNION ALL SELECT 'SW' UNION ALL SELECT 'TO' UNION ALL SELECT 'DV' UNION ALL SELECT 'JK' 
  UNION ALL SELECT 'KT' UNION ALL SELECT 'PD' UNION ALL SELECT 'VT'
  UNION ALL SELECT 'DT' UNION ALL SELECT 'S2' UNION ALL SELECT 'S1' UNION ALL SELECT 'BV' 
  UNION ALL SELECT 'ZT' UNION ALL SELECT 'CT' UNION ALL SELECT 'LE' UNION ALL SELECT 'S5' 
  UNION ALL SELECT 'RL' UNION ALL SELECT 'SS' UNION ALL SELECT 'TL' UNION ALL SELECT 'BR'
)

SELECT 
  '25F 의류 전체' AS category,
  SUM(TAG_SALE_AMT) AS gross_sales_twd,
  SUM(VAT_EXC_ACT_SALE_AMT) AS net_sales_twd,
  SUM(TAG_SALE_AMT) * 0.2475 AS gross_sales_hkd,
  SUM(VAT_EXC_ACT_SALE_AMT) * 0.2475 AS net_sales_hkd,
  ROUND(SUM(TAG_SALE_AMT) * 0.2475 / 1000000, 1) || 'M' AS gross_sales_hkd_m,
  ROUND(SUM(VAT_EXC_ACT_SALE_AMT) * 0.2475 / 1000000, 1) || 'M' AS net_sales_hkd_m,
  CASE 
    WHEN SUM(TAG_SALE_AMT) > 0 
    THEN ROUND(((SUM(TAG_SALE_AMT) - SUM(VAT_EXC_ACT_SALE_AMT)) / SUM(TAG_SALE_AMT)) * 100, 1) 
    ELSE 0 
  END AS discount_rate_pct,
  COUNT(DISTINCT PRDT_CD) AS product_count,
  COUNT(DISTINCT LOCAL_SHOP_CD) AS shop_count,
  MIN(SALE_DT) AS min_date,
  MAX(SALE_DT) AS max_date
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    -- TW 정상+아울렛+온라인
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3',
    'TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories)

UNION ALL

-- 카테고리별 상위 10개
SELECT 
  SUBSTR(PART_CD, 3, 2) AS category,
  SUM(TAG_SALE_AMT),
  SUM(VAT_EXC_ACT_SALE_AMT),
  SUM(TAG_SALE_AMT) * 0.2475,
  SUM(VAT_EXC_ACT_SALE_AMT) * 0.2475,
  ROUND(SUM(TAG_SALE_AMT) * 0.2475 / 1000000, 1) || 'M',
  ROUND(SUM(VAT_EXC_ACT_SALE_AMT) * 0.2475 / 1000000, 1) || 'M',
  CASE 
    WHEN SUM(TAG_SALE_AMT) > 0 
    THEN ROUND(((SUM(TAG_SALE_AMT) - SUM(VAT_EXC_ACT_SALE_AMT)) / SUM(TAG_SALE_AMT)) * 100, 1) 
    ELSE 0 
  END,
  COUNT(DISTINCT PRDT_CD),
  COUNT(DISTINCT LOCAL_SHOP_CD),
  MIN(SALE_DT),
  MAX(SALE_DT)
FROM SAP_FNF.DW_HMD_SALE_D
WHERE 
  (CASE WHEN BRD_CD IN ('M','I') THEN 'M' ELSE BRD_CD END) = 'M'
  AND SESN = '25F'
  AND SALE_DT BETWEEN '2026-01-01' AND '2026-01-31'
  AND LOCAL_SHOP_CD IN (
    'T01','T02','T03','T06','T08','T10','T11','T12','T13','T14','T16','T17','T18',
    'D01','D03','D04','DE1','DE2',
    'TU1','TU2','TU3',
    'TE1','TE2','TE3'
  )
  AND SUBSTR(PART_CD, 3, 2) IN (SELECT cat FROM apparel_categories)
GROUP BY SUBSTR(PART_CD, 3, 2)
ORDER BY gross_sales_twd DESC
LIMIT 11;
